name: huduma360
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  intl: ^0.19.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/