// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ukztlyvyxtfkhdtyejqi

class SupabaseConfig {
  static const String supabaseUrl = 'https://ukztlyvyxtfkhdtyejqi.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrenRseXZ5eHRma2hkdHllanFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0ODU4MjMsImV4cCI6MjA3NjA2MTgyM30.3mzwiLq2Qs7A_GoiVk_H8qi8lzmiqL9rT6u8xr7O5mU';
}
